export function jobpostKeywordParser(title, content, jobpostId) {
    const keywords = [
        { keyword: '정규직', keywordCode: 5000 },
        { keyword: '계약직', keywordCode: 5001 },
        { keyword: '아르바이트', keywordCode: 5002 },
        { keyword: '인턴직', keywordCode: 5003 },
        { keyword: '프리랜서', keywordCode: 5004 },
        { keyword: '파트', keywordCode: 5005 },
        { keyword: '위촉직', keywordCode: 5006 },
        { keyword: '판견직', keywordCode: 5007 },
        { keyword: '전임', keywordCode: 5008 },
        { keyword: '병역특례', keywordCode: 5009 },
        { keyword: '교육생', keywordCode: 5010 },
        { keyword: '해외취업', keywordCode: 5011 },
        { keyword: '인턴', keywordCode: 6000 },
        { keyword: '사원', keywordCode: 6001 },
        { keyword: '주임', keywordCode: 6002 },
        { keyword: '계장', keywordCode: 6003 },
        { keyword: '대리', keywordCode: 6004 },
        { keyword: '과장', keywordCode: 6005 },
        { keyword: '차장', keywordCode: 6006 },
        { keyword: '부장', keywordCode: 6007 },
        { keyword: '이사', keywordCode: 6008 },
        { keyword: '경력무관', keywordCode: 7000 },
        { keyword: '신입', keywordCode: 7001 },
        { keyword: '경력', keywordCode: 7002 },
        { keyword: '학력무관', keywordCode: 8000 },
        { keyword: '고졸', keywordCode: 8001 },
        { keyword: '초대졸', keywordCode: 8002 },
        { keyword: '대졸', keywordCode: 8003 },
        { keyword: '석사', keywordCode: 8004 },
        { keyword: '박사', keywordCode: 8005 },
        { keyword: '기타', keywordCode: 9000 },
        { keyword: '농림어업', keywordCode: 9001 },
        { keyword: '광업', keywordCode: 9002 },
        { keyword: '제조', keywordCode: 9003 },
        { keyword: '전기 가스 증기 수도', keywordCode: 9004 },
        { keyword: '자원환경복원', keywordCode: 9005 },
        { keyword: '건설', keywordCode: 9006 },
        { keyword: '도소매업', keywordCode: 9007 },
        { keyword: '운수', keywordCode: 9008 },
        { keyword: '숙박 음식점', keywordCode: 9009 },
        { keyword: 'IT 방송통신 출판 영상', keywordCode: 9010 },
        { keyword: '금융 보험', keywordCode: 9011 },
        { keyword: '부동산 임대', keywordCode: 9012 },
        { keyword: '과학기술', keywordCode: 9013 },
        { keyword: '사업시설관리 사업지원', keywordCode: 9014 },
        { keyword: '공공행정 국방 사회보장', keywordCode: 9015 },
        { keyword: '교육', keywordCode: 9016 },
        { keyword: '보건 사회복지', keywordCode: 9017 },
        { keyword: '예술 스포츠', keywordCode: 9018 },
        { keyword: '협회 수리 개인서비스', keywordCode: 9019 },
        { keyword: '가구 내 고용활동 외', keywordCode: 9020 },
        { keyword: '국제 외국기관', keywordCode: 9021 },
        { keyword: '게임개발', keywordCode: 10000 },
        { keyword: '기술지원', keywordCode: 10001 },
        { keyword: '데이터분석', keywordCode: 10002 },
        { keyword: '데이터엔지니어', keywordCode: 10003 },
        { keyword: '백엔드 서버개발', keywordCode: 10004 },
        { keyword: '보안관제', keywordCode: 10005 },
        { keyword: '보안컨설팅', keywordCode: 10006 },
        { keyword: '앱개발', keywordCode: 10007 },
        { keyword: '웹개발', keywordCode: 10008 },
        { keyword: '웹마스터', keywordCode: 10009 },
        { keyword: '유지보수', keywordCode: 10010 },
        { keyword: '정보보안', keywordCode: 10011 },
        { keyword: '퍼블리셔', keywordCode: 10012 },
        { keyword: '프론트엔드', keywordCode: 10013 },
        { keyword: 'CISO', keywordCode: 10014 },
        { keyword: 'CPO', keywordCode: 10015 },
        { keyword: 'DBA', keywordCode: 10016 },
        { keyword: 'FAE', keywordCode: 10017 },
        { keyword: 'GM', keywordCode: 10018 },
        { keyword: 'ICT컨설팅', keywordCode: 10019 },
        { keyword: 'IT컨설팅', keywordCode: 10020 },
        { keyword: 'QA', keywordCode: 10021 },
        { keyword: 'SE 시스템엔지니어', keywordCode: 10022 },
        { keyword: 'SI개발', keywordCode: 10023 },
        { keyword: 'SQA', keywordCode: 10024 },
    ]

    const stacks = [
        { stack: 'Agit', category: '협업툴' },
        { stack: 'Airflow', category: '데이터' },
        { stack: 'Alamofire', category: '모바일' },
        { stack: 'Angular', category: '프론트엔드' },
        { stack: 'Ansible', category: '데브옵스' },
        { stack: 'Apollo', category: '백엔드' },
        { stack: 'Appium', category: '테스팅툴' },
        { stack: 'ArangoDB', category: '데이터베이스' },
        { stack: 'Arcus', category: '데이터베이스' },
        { stack: 'Argo CD', category: '데브옵스' },
        { stack: 'Armeria', category: '백엔드' },
        { stack: 'Asana', category: '협업툴' },
        { stack: 'ASP.NET', category: '백엔드' },
        { stack: 'AWS Athena', category: '데이터' },
        { stack: 'AWS AuroraDB', category: '데이터베이스' },
        { stack: 'AWS CodeBuild', category: '데브옵스' },
        { stack: 'AWS CodeDeploy', category: '데브옵스' },
        { stack: 'AWS CodePipeline', category: '데브옵스' },
        { stack: 'AWS DocumentDB', category: '데이터베이스' },
        { stack: 'AWS DynamoDB', category: '데이터베이스' },
        { stack: 'AWS Kinesis', category: '백엔드' },
        { stack: 'AWS MariaDB', category: '데이터베이스' },
        { stack: 'AWS Redshift', category: '데이터' },
        { stack: 'AWS SES', category: '백엔드' },
        { stack: 'AWS SNS', category: '백엔드' },
        { stack: 'AWS SQS', category: '백엔드' },
        { stack: 'Azure DevOps', category: '데브옵스' },
        { stack: 'BackboneJS', category: '프론트엔드' },
        { stack: 'Bazel', category: '모바일' },
        { stack: 'Bitbucket', category: '데브옵스' },
        { stack: 'Bitrise', category: '모바일' },
        { stack: 'Capistrano', category: '데브옵스' },
        { stack: 'CassandraDB', category: '데이터베이스' },
        { stack: 'Celery', category: '백엔드' },
        { stack: 'Central Dogma', category: '데브옵스' },
        { stack: 'Ceph', category: '데이터베이스' },
        { stack: 'Circle CI', category: '데브옵스' },
        { stack: 'Clickhouse', category: '데이터' },
        { stack: 'Clojure', category: '언어' },
        { stack: 'CockroachDB', category: '데이터베이스' },
        { stack: 'CodeIgniter', category: '백엔드' },
        { stack: 'Confluence', category: '협업툴' },
        { stack: 'Couchbase', category: '데이터베이스' },
        { stack: 'C++', category: '언어' },
        { stack: 'C#', category: '언어' },
        { stack: 'Cubrid', category: '데이터베이스' },
        { stack: 'Cucumber', category: '테스팅툴' },
        { stack: 'Cypress', category: '테스팅툴' },
        { stack: 'Dagger', category: '모바일' },
        { stack: 'Dart', category: '언어' },
        { stack: 'Discord', category: '협업툴' },
        { stack: 'Django', category: '백엔드' },
        { stack: 'Docker', category: '데브옵스' },
        { stack: 'Docusaurus', category: '프론트엔드' },
        { stack: 'Dooray', category: '협업툴' },
        { stack: 'Drone', category: '데브옵스' },
        { stack: 'Dropwizard', category: '백엔드' },
        { stack: 'Druid', category: '데이터' },
        { stack: 'ElasticSearch', category: '데이터베이스' },
        { stack: 'Electron', category: '프론트엔드' },
        { stack: 'Elixir', category: '언어' },
        { stack: 'EmberJS', category: '프론트엔드' },
        { stack: 'Emotion', category: '프론트엔드' },
        { stack: 'Envoy', category: '데브옵스' },
        { stack: 'Enzyme', category: '테스팅툴' },
        { stack: 'ExoPlayer', category: '모바일' },
        { stack: 'ExpressJS', category: '백엔드' },
        { stack: 'Falcon', category: '백엔드' },
        { stack: 'FastAPI', category: '백엔드' },
        { stack: 'Fastify', category: '백엔드' },
        { stack: 'Fastlane', category: '모바일' },
        { stack: 'Fiber', category: '백엔드' },
        { stack: 'Flask', category: '백엔드' },
        { stack: 'Flink', category: '데이터' },
        { stack: 'Flow', category: '협업툴' },
        { stack: 'Fluentd', category: '데이터' },
        { stack: 'Flutter', category: '모바일' },
        { stack: 'Gatsby', category: '프론트엔드' },
        { stack: 'Gin', category: '백엔드' },
        { stack: 'Github', category: '데브옵스' },
        { stack: 'Github Action', category: '데브옵스' },
        { stack: 'Gitlab', category: '데브옵스' },
        { stack: 'Glide', category: '모바일' },
        { stack: 'Go', category: '언어' },
        { stack: 'Go CD', category: '데브옵스' },
        { stack: 'Google BigQuery', category: '데이터' },
        { stack: 'Google Cloud Build', category: '데브옵스' },
        { stack: 'Google Data Studio', category: '데이터' },
        { stack: 'Google Firebase', category: '모바일' },
        { stack: 'Google Firestore', category: '모바일' },
        { stack: 'Grafana', category: '데이터' },
        { stack: 'GraphQL', category: '프론트엔드' },
        { stack: 'Greenplum', category: '데이터베이스' },
        { stack: 'GRPC', category: '백엔드' },
        { stack: 'Gulp', category: '데브옵스' },
        { stack: 'H2', category: '데이터베이스' },
        { stack: 'Hadoop', category: '데이터' },
        { stack: 'Harbor', category: '데브옵스' },
        { stack: 'Hazelcast', category: '데이터' },
        { stack: 'HBase', category: '데이터' },
        { stack: 'Helm', category: '데브옵스' },
        { stack: 'Hibernate', category: '백엔드' },
        { stack: 'Hive', category: '데이터' },
        { stack: 'Hugo', category: '프론트엔드' },
        { stack: 'Immer', category: '프론트엔드' },
        { stack: 'Impala', category: '데이터' },
        { stack: 'InfluxDB', category: '데이터베이스' },
        { stack: 'Istio', category: '데브옵스' },
        { stack: 'Jaeger', category: '데브옵스' },
        { stack: 'Jandi', category: '협업툴' },
        { stack: 'Jasmine', category: '테스팅툴' },
        { stack: 'Java', category: '언어' },
        { stack: 'Javascript', category: '언어' },
        { stack: 'Jenkins', category: '데브옵스' },
        { stack: 'Jest', category: '테스팅툴' },
        { stack: 'Jira', category: '협업툴' },
        { stack: 'Jotai', category: '프론트엔드' },
        { stack: 'JUnit', category: '테스팅툴' },
        { stack: 'Kafka', category: '데이터' },
        { stack: 'Kakaotalk', category: '협업툴' },
        { stack: 'KakaoWork', category: '협업툴' },
        { stack: 'Karma', category: '테스팅툴' },
        { stack: 'Karpenter', category: '데브옵스' },
        { stack: 'Keras', category: '데이터' },
        { stack: 'Kibana', category: '데이터' },
        { stack: 'Koa', category: '백엔드' },
        { stack: 'Kotlin', category: '언어' },
        { stack: 'Ktor', category: '백엔드' },
        { stack: 'Kube-Bench', category: '데브옵스' },
        { stack: 'Kubeflow', category: '데이터' },
        { stack: 'Kubernetes', category: '데브옵스' },
        { stack: 'Kudu', category: '데이터' },
        { stack: 'Laravel', category: '백엔드' },
        { stack: 'Linkerd', category: '데브옵스' },
        { stack: 'Liquibase', category: '백엔드' },
        { stack: 'Locust', category: '테스팅툴' },
        { stack: 'Looker', category: '데이터' },
        { stack: 'Lottie', category: '모바일' },
        { stack: 'Lua', category: '언어' },
        { stack: 'Luigi', category: '데이터' },
        { stack: 'Memcached', category: '데이터베이스' },
        { stack: 'Metabase', category: '데이터' },
        { stack: 'Meteor', category: '프론트엔드' },
        { stack: 'Microsoft-Teams', category: '협업툴' },
        { stack: 'MLflow', category: '데이터' },
        { stack: 'MobX', category: '프론트엔드' },
        { stack: 'Mocha', category: '테스팅툴' },
        { stack: 'Mockito', category: '테스팅툴' },
        { stack: 'Monday', category: '협업툴' },
        { stack: 'MongoDB', category: '데이터베이스' },
        { stack: 'Moya', category: '모바일' },
        { stack: 'MSSQL', category: '데이터베이스' },
        { stack: 'MyBatis', category: '백엔드' },
        { stack: 'MySQL', category: '데이터베이스' },
        { stack: 'Naver Works', category: '협업툴' },
        { stack: 'Neo4j', category: '데이터베이스' },
        { stack: 'NestJS', category: '백엔드' },
        { stack: 'Netty', category: '백엔드' },
        { stack: 'NextJS', category: '프론트엔드' },
        { stack: 'Nexus', category: '데브옵스' },
        { stack: 'nGrinder', category: '테스팅툴' },
        { stack: 'NIFI', category: '데이터' },
        { stack: 'NodeJS', category: '백엔드' },
        { stack: 'Notion', category: '협업툴' },
        { stack: 'NuxtJS', category: '프론트엔드' },
        { stack: 'Objective-C', category: '언어' },
        { stack: 'OpenEBS', category: '데브옵스' },
        { stack: 'OpenGL', category: '프론트엔드' },
        { stack: 'OracleDB', category: '데이터베이스' },
        { stack: 'Packer', category: '데브옵스' },
        { stack: 'Perl', category: '언어' },
        { stack: 'Phoenix', category: '백엔드' },
        { stack: 'PHP', category: '언어' },
        { stack: 'Playwright', category: '테스팅툴' },
        { stack: 'PostgreSQL', category: '데이터베이스' },
        { stack: 'Presto', category: '데이터' },
        { stack: 'Prometheus', category: '데이터' },
        { stack: 'Puppeteer', category: '테스팅툴' },
        { stack: 'Python', category: '언어' },
        { stack: 'Pytorch', category: '데이터' },
        { stack: 'R', category: '언어' },
        { stack: 'RabbitMQ', category: '백엔드' },
        { stack: 'Rancher', category: '데브옵스' },
        { stack: 'Ranger', category: '데이터' },
        { stack: 'Ray', category: '데이터' },
        { stack: 'React Context', category: '프론트엔드' },
        { stack: 'ReactiveX', category: '프론트엔드' },
        { stack: 'ReactJS', category: '프론트엔드' },
        { stack: 'React Native', category: '모바일' },
        { stack: 'ReactorKit', category: '모바일' },
        { stack: 'React Query', category: '프론트엔드' },
        { stack: 'Realm', category: '모바일' },
        { stack: 'Recoil', category: '프론트엔드' },
        { stack: 'Redash', category: '데이터' },
        { stack: 'Redis', category: '데이터베이스' },
        { stack: 'Redux', category: '프론트엔드' },
        { stack: 'Relay', category: '프론트엔드' },
        { stack: 'ReScript', category: '언어' },
        { stack: 'Rest-Assured', category: '테스팅툴' },
        { stack: 'Retrofit', category: '모바일' },
        { stack: 'RIBs', category: '모바일' },
        { stack: 'RocksDB', category: '데이터베이스' },
        { stack: 'Ruby', category: '언어' },
        { stack: 'Ruby on Rails', category: '백엔드' },
        { stack: 'Rundeck', category: '데브옵스' },
        { stack: 'Rust', category: '언어' },
        { stack: 'Saltstack', category: '데브옵스' },
        { stack: 'Sanic', category: '백엔드' },
        { stack: 'Scala', category: '언어' },
        { stack: 'Selenium', category: '테스팅툴' },
        { stack: 'Sinon', category: '테스팅툴' },
        { stack: 'Slack', category: '협업툴' },
        { stack: 'SnapKit', category: '모바일' },
        { stack: 'Snowflake', category: '데이터' },
        { stack: 'Solr', category: '데이터베이스' },
        { stack: 'Sonarqube', category: '테스팅툴' },
        { stack: 'Spark', category: '데이터' },
        { stack: 'Spinnaker', category: '데브옵스' },
        { stack: 'Spring', category: '백엔드' },
        { stack: 'SpringBoot', category: '백엔드' },
        { stack: 'Storybook', category: '프론트엔드' },
        { stack: 'Styled-Components', category: '프론트엔드' },
        { stack: 'Superset', category: '데이터' },
        { stack: 'Svelte', category: '프론트엔드' },
        { stack: 'Swagger', category: '백엔드' },
        { stack: 'Swift', category: '언어' },
        { stack: 'Tableau', category: '데이터' },
        { stack: 'Tailwind', category: '프론트엔드' },
        { stack: 'Telegram', category: '협업툴' },
        { stack: 'Tensorflow', category: '데이터' },
        { stack: 'Terraform', category: '데브옵스' },
        { stack: 'Testing Library', category: '테스팅툴' },
        { stack: 'Thrift', category: '백엔드' },
        { stack: 'Traefik', category: '데브옵스' },
        { stack: 'Travis CI', category: '데브옵스' },
        { stack: 'Trello', category: '협업툴' },
        { stack: 'Trino', category: '데이터' },
        { stack: 'Tuist', category: '모바일' },
        { stack: 'Typescript', category: '언어' },
        { stack: 'Unity', category: '프론트엔드' },
        { stack: 'Vault', category: '데브옵스' },
        { stack: 'VueJS', category: '프론트엔드' },
        { stack: 'Vuex', category: '프론트엔드' },
        { stack: 'WebRTC', category: '백엔드' },
        { stack: 'Zabbix', category: '데브옵스' },
        { stack: 'Zeppelin', category: '데이터' },
        { stack: 'Zipkin', category: '데이터' },
        { stack: 'Zustand', category: '프론트엔드' },
    ]

    const contentKeywords = []
    const contentStacks = []

    if (typeof content === 'object') content = JSON.stringify(content)
    content = title + content
    content = content.replace(/\s/g, '')
    content = content.toLowerCase()

    let keyword
    for (let i = 0; i < keywords.length; i++) {
        keyword = keywords[i].keyword.split(' ')
        for (let j = 0; j < keyword.length; j++) {
            if (content.includes(keyword[j].toLowerCase())) {
                contentKeywords.push({
                    keywordCode: keywords[i].keywordCode,
                    jobpostId: jobpostId,
                })
                break
            }
        }
    }

    for (let i = 0; i < stacks.length; i++) {
        if (content.includes(stacks[i].stack.toLowerCase())) {
            contentStacks.push({
                stack: stacks[i].stack,
                category: stacks[i].category,
            })
        }
    }

    console.log(contentKeywords)
    console.log(contentStacks)
}

jobpostKeywordParser(
    '연구소 오디오 워터마크 및 플러그인 연구 개발직',
    {
        requirements:
            '• Java(Kotlin) & Spring Framework 기반 웹 서버 개발 경력 7년 이상\n• ORM (JPA, Hibernate)기반 개발 역량을 보유하신 분\n• 대규모 서비스 설계, 구축, 운영 경험이 있으신 분\n• 다양한 Stakeholder, 개발자와 함께 복잡한 비즈니스 요구사항을 풀어내며 적극적이고 원활한 커뮤니케이션이 가능하신 분',
        main_tasks:
            '[‍마이리얼트립 제품 개발 조직은 이렇게 일합니다.]\n\n마이리얼트립은 고객과 데이터를 중심의 최고의 여행 서비스를 개발합니다. \n\n전 세계의 항공, 숙박, 교통, 투어&액티비티 상품들을 효과적으로 관리하고, 서로 다른 상품들의 경험을 통일하여 쉽고, 편리한 탐색/예약/구매 경험을 제공하기 위해 노력합니다. 최고 수준의 기술로 기존에 존재하지 않는 새로운 여행 경험을 제시하고자 합니다.\n\n• 데이터를 기반으로 고객에게 최상의 임팩트를 제공하기 위해 모든 구성원이 함께 치열하게 고민합니다. 데이터를 기반으로 문제를 정의하고, 제품/사업/운영 조직이 함께 해결책을 모색합니다. 모든 조직이 최상의 결과물을 얻기 위해 치열하게 도전합니다.\n\n• 고객의 소리에 집중합니다. 우리가 고객이 가지고 있는 문제에 집중하며, 그 문제를 단순히 풀어내는 것이 아니라, 10배, 100배 더 잘 풀어내기 위해 끊임없이 고민합니다.\n\n• 상호존중과 신뢰를 기반으로 함께 성장합니다. 나이/연차와 무관한 강한 책임감을 가지고 각자 맡은 업무를 주도적으로 진행하며, 동료들과 더 나은 서비스를 위하여 자유롭게 의견을 개진합니다. 그리고 경쟁이 아닌 함께 성장하는 문화를 만들어가고자 합니다.\n\n\n[마이리얼트립의 미들레이어 개발 팀장은 이런 일을 해요.]\n\n미들레이어 개발팀은 MSA로 세분화된 여러 버티컬(투어&액티비티, 숙박, 교통, 항공, 커뮤니티 등)의 상품과 컨텐츠를 취합하여 서비스하고 있습니다.\n\n메인홈, 도시홈과 같은 중요 진입점을 담당하면서 보다 안정적이고 빠른 서비스를 제공하는 것을 목표로 하고 있습니다. \n\n또한 모바일 앱 배포 없이 유연한 서비스 적용을 위하여 Server Driven UI 를 도입하고 있습니다.\n\n앞으로 담당할 주요 업무는 아래와 같습니다.\n\n• 메인홈, 도시홈과 같은 중요 진입점 페이지 개발 & 운영\n• Server Driven UI 를 위한 프레임웍과 운영툴 개발\n• 팀원들의 성장을 돕는 People management와 채용에 적극적으로 참여',
        intro: 'The North Star\n“Travel Everyday” 마이리얼트립은 누구나 여행의 즐거움을 더 자주 느낄 수 있는 세상을 만들어 가고 있습니다. 미션을 향해 거침없이 도전하는 팀과 함께 여행의 새로운 패러다임을 만들어 보세요.\n\n마이리얼트립은 여행을 떠나기 위해 필요한 모든 것을 한 곳에서 검색하고 예약할 수 있는 국내 최고의 Travel Super App입니다.\n\n2012년 가이드 투어 서비스를 시작으로 2016년 숙박, 2018년 항공, 2019년 패키지까지 출시하며 여행에 필요한 모든 경험을 고객에게 제공하고 있습니다. 마이리얼트립은 차별화된 기술을 바탕으로 새로운 여행 방식을 만들어가고, 코로나 시대 이후의 여행을 준비하고 있습니다.\n\n마이리얼트립은 2018년 거래액 1,300억 원, 2019년 3,600억 원을 달성해 매년 300%씩 고속 성장을 지속해왔습니다. 또한 이러한 성과를 바탕으로 알토스벤처스,스마일게이트인베스트먼트,IMM인베스트먼트와 같은 국내외 유수의 투자사로부터 누적 총 824억 원의 자금을 유치했습니다.\n\n마이리얼트립 팀과 함께 여행의 미래를 그려나갈 분들을 모십니다.\n\n- 마이리얼트립의 플랫폼 전략 : https://bit.ly/30MxgiW\n- 마이리얼트립 국내 사업 피버팅 전략 : https://bit.ly/3cPtmh8\n\n* 채용공통사항\n[채용절차]\n- 서류전형 ＞ 1차 면접 ＞ 2차 면접 ＞ 처우협의 ＞ 입사\n- 기술 면접 진행 전 면접관의 판단에 따라 전화 인터뷰 혹은 온라인 코딩테스트 절차가 추가될 수 있습니다.\n- 기술 면접은 지원분야 기술 Stack 관련 질문으로 진행됩니다.\n- 각 전형별 결과는 15일 이내에 안내 드립니다.\n\n[지원서류]\n마이리얼트립은 별도의 정해진 양식 없이 자유형식의 지원서를 받고 있습니다. 지원하신 직무에 본인의 강점이 잘 드러날 수 있도록 자유롭게 작성해 주세요.\n \n＜지원서 작성 Tip＞\n- 지원하시는 직무의 주요 업무와 자격 요건에 부합하는 직무 경험과 성과가 잘 드러나도록 작성해주세요.\n- 개발 직무의 경우, 지원서 상에 수행하신 프로젝트 별 기술 스택을 잘 기재해 주시기 바랍니다.\n- 지원서 내에 본인의 강점이 잘 드러나는 웹 링크(깃허브, 노션, 구글드라이브 등)은 자유롭게 첨부해주세요. (접근 권한은 오픈한 상태로 공유해주세요.)\n- 직무와 무관한 개인정보(주민번호, 가족사항, 신체사항, 연봉 정보 등)는 제외해 주세요.\n- 문서 형식은 PDF 파일로 제출해주세요.\n\n[근무환경] \n- 근무형태 : 정규직 (수습기간 3개월 후 정규직 전환 심사)\n- 근무시간 : 주5일 (월~금)\n- 근무제도 : 자율출퇴근제, 재택근무제\n- 근무지 : 서울시 서초구 강남대로 311 드림플러스 강남\n\n마이리얼트립이 일하는 방법 (http://www.wanted.co.kr/events/21_10_s01_b02)',
        benefits:
            '- 여행상품 지원 (마이리얼트립 포인트 - 연 150만원, 지인쿠폰 월 5만원)\n- 다양한 휴가제도 (생일 반차, 가족행사 휴가 2일, 경조사 휴가 등)\n- 자기계발비 지원 (체력단련, 도서구매, 문화생활 - 연 180만원)\n- 직무교육비 지원 (직무 관련 강의, 컨퍼런스 - 교육비 80% 지원)\n- 점심 식비 지원\n- 업무장비 지원 (직군 별 최신 장비 제공)\n- 건강검진 지원 (연 1회)\n- 실손보험 제공 (본인 포함 4인)\n- 워크샵 운영 (연 1회)',
        preferred_points:
            '• 특정 도메인을 담당하는 개발팀을 리딩/매니징한 경험\n• MSA(Microservice Architecture), EDA(Event Driven Architecture) 개발 경험\n• 모바일 앱 개발 경험 또는 모바일 아키텍처를 이해하고 협업한 경험\n• 조직의 기술과 문화를 지속해서 높여나가기 위한 활동 경험',
    },
    1
)
